//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AoC2025.Day1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AoC2025.Day1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L40
        ///R27
        ///R20
        ///R12
        ///R28
        ///L9
        ///R31
        ///R45
        ///L19
        ///R2
        ///L25
        ///L46
        ///R1
        ///R26
        ///L44
        ///L27
        ///R11
        ///R41
        ///L11
        ///R14
        ///R33
        ///L2
        ///R24
        ///L8
        ///L31
        ///R3
        ///R3
        ///R17
        ///L14
        ///L8
        ///L16
        ///R44
        ///L39
        ///L7
        ///R2
        ///L17
        ///L2
        ///R33
        ///R50
        ///L33
        ///R45
        ///L33
        ///L22
        ///R35
        ///R50
        ///L24
        ///R47
        ///L50
        ///L49
        ///R14
        ///R13
        ///R10
        ///R45
        ///R96
        ///R4
        ///R29
        ///L29
        ///L34
        ///L66
        ///L59
        ///L69
        ///R18
        ///R56
        ///R54
        ///R5
        ///L20
        ///R92
        ///L38
        ///R99
        ///R62
        ///L87
        ///R20
        ///R41
        ///L97
        ///L77
        ///L93
        ///R85
        ///L92
        ///R82
        ///L82
        ///R71
        ///R28
        ///L94
        ///L96
        ///R97
        ///R10
        ///L16
        ///L48
        ///L52
        ///R92
        ///L16
        ///L44
        ///L32
        ///R72
        ///L10
        ///R38
        ///L45
        ///R17
        ///R7
        ///R14
        ///R7
        ///L69
        ///L44
        ///L87
        ///R87
        ///L6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string InputDay1a {
            get {
                return ResourceManager.GetString("InputDay1a", resourceCulture);
            }
        }
    }
}
